lethal-guitar/RigelEngine

CMakeLists.txt
src/data/duke_script.hpp
src/data/map.hpp
src/engine/rendering_system.cpp
src/game_logic/collectable_components.hpp
src/loader/duke_script_loader.cpp
src/loader/rle_compression.hpp
src/loader/voc_decoder.cpp
src/main.cpp
src/ui/menu_element_renderer.hpp
src/ui/movie_player.hpp

@lethal-guitar: merge at will!

A few fixes to build on OSX

---

README.md
src/CMakeLists.txt
src/data/map.cpp
src/data/map.hpp
src/data/player_data.hpp
src/engine/base_components.hpp
src/engine/map_renderer.cpp
src/engine/map_renderer.hpp
src/engine/physics_system.cpp
src/engine/physics_system.hpp
src/engine/rendering_system.cpp
src/engine/rendering_system.hpp
src/engine/visual_components.hpp
src/game_logic/entity_factory.cpp
src/game_logic/entity_factory.hpp
src/game_logic/player_control_system.cpp
src/game_logic/player_control_system.hpp
src/ingame_mode.cpp
src/ingame_mode.hpp
src/loader/level_loader.cpp
src/ui/bonus_screen.cpp
src/ui/hud_renderer.cpp

Refactoring in preparation of implementing player damage/death.

Player damage preparations, plus cleanups

---

README.md
src/CMakeLists.txt
src/engine/rendering_system.cpp
src/engine/timing.hpp
src/engine/visual_components.hpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp
src/game_logic/player/damage_system.cpp
src/game_logic/player/damage_system.hpp
src/game_logic/player_control_system.cpp
src/game_logic/player_control_system.hpp
src/game_logic/player_interaction_system.cpp
src/game_logic/trigger_components.hpp
src/ingame_mode.cpp
src/ingame_mode.hpp

The player can now take damage, replenish his health by collecting health items, and die. The latter will restart the level.
Closes #28

Player damage/death

---

src/engine/rendering_system.cpp
src/engine/visual_components.hpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp

Fixes appearance of the slime dripping pipe (actor ID `117`).

Draw slime dripping pipe on top of map geometry

---

.appveyor.yml
src/CMakeLists.txt
src/base/spatial_types_printing.hpp
src/engine/physical_components.hpp
src/engine/physics_system.cpp
src/engine/physics_system.hpp
src/game_logic/damage_components.hpp
src/game_logic/damage_infliction_system.cpp
src/game_logic/damage_infliction_system.hpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp
src/game_logic/entity_factory.hpp
src/game_logic/player/attack_system.cpp
src/game_logic/player/attack_system.hpp
src/game_logic/player/damage_system.cpp
src/game_logic/player_control_system.cpp
src/game_logic/player_control_system.hpp
src/ingame_mode.cpp
src/ingame_mode.hpp
src/main.cpp
test/CMakeLists.txt
test/test_player_attack_system.cpp

Implements the most essential basics of shooting for the player. For now, only the normal weapon works. Also, there are no animation, muzzle flash effects or particles yet, the position of the projectile is not always correct, and other aspects are not quite right.
First step towards #19

Basic shooting for player

---

src/CMakeLists.txt
src/game_logic/ai/security_camera.cpp
src/game_logic/ai/security_camera.hpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp
src/ingame_mode.cpp

Implement security camera "enemy"

---

CMakeLists.txt
src/CMakeLists.txt
src/base/spatial_types.hpp
src/engine/debugging_system.cpp
src/engine/debugging_system.hpp
src/engine/rendering_system.cpp
src/game.cpp
src/game.hpp
src/game_mode.hpp
src/game_session_mode.cpp
src/game_session_mode.hpp
src/ingame_mode.cpp
src/ingame_mode.hpp
src/main.cpp
src/sdl_utils/rect_tools.hpp
src/ui/fps_display.cpp
src/ui/fps_display.hpp
src/ui/menu_element_renderer.cpp
src/ui/menu_element_renderer.hpp
test/test_player_animation_system.cpp
test/utils.hpp

Allows visualizing bounding boxes and world collision data, as well as showing player position/velocity and scroll offset. Adds a command line option to start a level with the player at some arbitrary position.

Debugging tools

---

src/CMakeLists.txt
src/engine/entity_tools.hpp
src/engine/physical_components.hpp
src/engine/physics_system.cpp
src/engine/physics_system.hpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp
src/game_logic/interaction/elevator.cpp
src/game_logic/interaction/elevator.hpp
src/game_logic/player/animation_system.cpp
src/game_logic/player/animation_system.hpp
src/game_logic/player/attack_system.cpp
src/game_logic/player/components.hpp
src/game_logic/player_movement_system.cpp
src/ingame_mode.cpp
test/CMakeLists.txt
test/test_duke_script_loader.cpp
test/test_elevator.cpp
test/test_physics_system.cpp
test/test_player_animation_system.cpp
test/test_player_attack_system.cpp

Implements the rocket elevator (called "turbo lift" in-game). This makes it possible to complete the first level, i.e. you can walk from the start to the end and reach level 2.
There are still some missing features:
* Flame/rocket exhaust animation for the elevator
* Do not try to move if already at the top/bottom
There is also an issue with the sound for the elevator, where some clicks and pops can be heard as the sound effect is played repeatedly. This seems to be a general issue with SDL_mixer or the way it's used, but it's especially prominent with the elevator sound.
Closes #16 
Closes #17

Rocket elevator

---

src/CMakeLists.txt
src/game_logic/entity_configuration.ipp
src/game_logic/interaction/teleporter.cpp
src/game_logic/interaction/teleporter.hpp
src/game_logic/player_interaction_system.cpp
src/game_logic/player_interaction_system.hpp
src/ingame_mode.cpp
src/ingame_mode.hpp
src/intro_demo_loop_mode.cpp

Closes #64 
Closes #67 
Also throw in a small fix to the Credits/Ordering Info display duration in the intro/attract loop.

Improve teleporter, implement backdrop switch

---

src/CMakeLists.txt
src/game_logic/ai/slime_pipe.cpp
src/game_logic/ai/slime_pipe.hpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp
src/game_logic/entity_factory.hpp
src/ingame_mode.cpp

Implement pipe dripping green slime/acid

---

src/CMakeLists.txt
src/base/math_tools.hpp
src/base/spatial_types.hpp
src/engine/physics_system.cpp
src/engine/physics_system.hpp
src/engine/rendering_system.cpp
src/engine/rendering_system.hpp
src/engine/sound_system.cpp
src/engine/visual_components.hpp
src/game_logic/ai/sliding_door.cpp
src/game_logic/ai/sliding_door.hpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp
src/game_logic/map_scroll_system.cpp
src/ingame_mode.cpp
src/loader/ega_image_decoder.cpp
src/loader/level_loader.cpp
src/loader/music_loader.cpp
src/loader/voc_decoder.cpp
src/ui/duke_script_runner.cpp
test/test_physics_system.cpp

Sliding doors

---

src/CMakeLists.txt
src/engine/random_number_generator.cpp
src/engine/random_number_generator.hpp
src/game_logic/ai/prisoner.cpp
src/game_logic/ai/prisoner.hpp
src/game_logic/damage_components.hpp
src/game_logic/damage_infliction_system.cpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp
src/ingame_mode.cpp
src/ingame_mode.hpp
src/ui/duke_script_runner.cpp

Implement prison cell monster

---

src/engine/renderer.cpp
src/engine/renderer.hpp
src/engine/rendering_system.cpp
src/engine/timing.cpp
src/engine/timing.hpp
src/engine/visual_components.hpp
src/game_logic/damage_infliction_system.cpp
src/game_main.cpp

Enemy damage flash

---

CMakeLists.txt
src/CMakeLists.txt
src/base/warnings.hpp
src/data/game_traits.cpp
src/game_logic/ai/messenger_drone.cpp
src/game_logic/ai/messenger_drone.hpp
src/game_logic/ai/sliding_door.cpp
src/game_logic/ai/slime_pipe.cpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp
src/game_logic/map_scroll_system.cpp
src/game_logic/player/animation_system.cpp
src/ingame_mode.cpp
src/loader/palette.cpp

Implement messenger drone (flying ship with screen)

---

src/CMakeLists.txt
src/data/sound_ids.hpp
src/engine/life_time_components.hpp
src/engine/life_time_system.cpp
src/engine/life_time_system.hpp
src/engine/sprite_tools.hpp
src/game_logic/ai/laser_turret.cpp
src/game_logic/ai/laser_turret.hpp
src/game_logic/ai/messenger_drone.cpp
src/game_logic/ai/prisoner.cpp
src/game_logic/damage_components.hpp
src/game_logic/damage_infliction_system.cpp
src/game_logic/damage_infliction_system.hpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp
src/game_logic/entity_factory.hpp
src/game_logic/player/damage_system.cpp
src/ingame_mode.cpp

Implement laser turret enemy

---

src/CMakeLists.txt
src/game_logic/ai/slime_blob.cpp
src/game_logic/ai/slime_blob.hpp
src/game_logic/damage_components.hpp
src/game_logic/damage_infliction_system.cpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp
src/game_logic/entity_factory.hpp
src/ingame_mode.cpp

Implement slime container

---

src/game_logic/ai/prisoner.cpp
src/game_logic/ai/prisoner.hpp
src/game_logic/entity_configuration.ipp

Fix grab sequence, add death animation

Improved prisoner

---

src/game_logic/ai/laser_turret.cpp
src/game_logic/ai/laser_turret.hpp
src/game_logic/ai/prisoner.cpp
src/game_logic/ai/prisoner.hpp
src/game_logic/ai/slime_blob.cpp
src/game_logic/ai/slime_blob.hpp
src/game_logic/damage_components.hpp
src/game_logic/damage_infliction_system.cpp
src/game_logic/damage_infliction_system.hpp
src/ingame_mode.cpp

Fix damage infliction: Revert to running after physics

---

src/CMakeLists.txt
src/data/game_traits.hpp
src/engine/debugging_system.cpp
src/game_logic/ai/rocket_turret.cpp
src/game_logic/ai/rocket_turret.hpp
src/game_logic/ai/slime_blob.cpp
src/game_logic/ai/slime_blob.hpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp
src/game_logic/entity_factory.hpp
src/ingame_mode.cpp

Closes #24 
Adding the sound-effect for the flying rockets is a follow-up.
Also includes some unrelated fixes/cleanups.

Rocket Turret enemy

---

src/CMakeLists.txt
src/data/map.cpp
src/engine/physics_system.cpp
src/game_logic/ai/blue_guard.cpp
src/game_logic/ai/blue_guard.hpp
src/game_logic/ai/prisoner.cpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp
src/game_logic/player/components.hpp
src/ingame_mode.cpp

Blue Guard enemy

---

src/engine/map_renderer.cpp
src/engine/map_renderer.hpp
src/engine/rendering_system.cpp
src/engine/rendering_system.hpp
src/engine/timing.cpp
src/engine/timing.hpp
src/engine/visual_components.hpp
src/game_logic/ai/blue_guard.cpp
src/game_logic/ai/blue_guard.hpp
src/game_logic/ai/messenger_drone.cpp
src/game_logic/ai/rocket_turret.cpp
src/game_logic/ai/rocket_turret.hpp
src/game_logic/entity_configuration.ipp
src/game_logic/interaction/force_field.cpp
src/game_logic/player/animation_system.cpp
src/game_logic/player/components.hpp
src/game_logic/player/damage_system.cpp
src/game_logic/player_movement_system.cpp
src/ingame_mode.cpp
src/ui/hud_renderer.cpp
src/ui/hud_renderer.hpp

* Fix Blue Guard player visibility check
* Add sound for Rocket Turret (closes #158 )
* fixes #71 
* closes #148

Refactoring, Cleanups and minor fixes and features

---

src/CMakeLists.txt
src/data/sound_ids.hpp
src/engine/earth_quake_effect.cpp
src/engine/earth_quake_effect.hpp
src/game_logic/ai/prisoner.cpp
src/game_logic/ai/slime_blob.cpp
src/game_logic/ai/slime_pipe.cpp
src/game_logic/damage_infliction_system.cpp
src/game_logic/entity_configuration.ipp
src/ingame_mode.cpp
src/ingame_mode.hpp

Implement earth quake effect, and some minor fixes.

---

src/CMakeLists.txt
src/engine/collision_checker.cpp
src/engine/collision_checker.hpp
src/game_logic/ai/blue_guard.cpp
src/game_logic/ai/blue_guard.hpp
src/game_logic/ai/slime_blob.cpp
src/game_logic/ai/slime_blob.hpp
src/game_logic/entity_configuration.ipp
src/ingame_mode.cpp

Implement Green Slime Blob enemy

---

src/CMakeLists.txt
src/engine/sprite_tools.hpp
src/game_logic/ai/hover_bot.cpp
src/game_logic/ai/hover_bot.hpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp
src/game_logic/entity_factory.hpp
src/game_logic/item_container.cpp
src/game_logic/item_container.hpp
src/game_logic/player/animation_system.cpp
src/game_logic/player/attack_system.cpp
src/game_logic/player/attack_system.hpp
src/game_logic/player/components.hpp
src/game_logic/player_interaction_system.cpp
src/game_logic/player_interaction_system.hpp
src/ingame_mode.cpp

closes #165 
closes #97 
closes #132 
closes #133

Hover Bot enemy and Item Boxes

---

src/CMakeLists.txt
src/engine/base_components.hpp
src/game_logic/ai/blue_guard.cpp
src/game_logic/ai/blue_guard.hpp
src/game_logic/ai/hover_bot.cpp
src/game_logic/ai/hover_bot.hpp
src/game_logic/ai/messenger_drone.cpp
src/game_logic/ai/messenger_drone.hpp
src/game_logic/ai/skeleton.cpp
src/game_logic/ai/skeleton.hpp
src/game_logic/ai/slime_blob.cpp
src/game_logic/ai/slime_blob.hpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp
src/game_logic/entity_factory.hpp
src/ingame_mode.cpp

Implement skeleton enemy

---

src/ingame_mode.cpp

Process player attacks after physics

---

src/engine/sound_system.cpp
src/engine/sound_system.hpp
src/game_main.cpp
src/game_main.ipp
src/loader/resource_loader.cpp
src/loader/resource_loader.hpp

Closes #48 
Also makes the first game mode fade in nicely.

Anti-piracy screen

---

src/CMakeLists.txt
src/data/player_data.hpp
src/game_logic/player/attack_system.hpp
src/game_logic/player/attack_system.ipp
src/ingame_mode.cpp
test/test_player_attack_system.cpp

Rapid fire buff

---

src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp
src/game_logic/entity_factory.hpp
src/game_logic/item_container.hpp

Soda can rocket

---

src/CMakeLists.txt
src/engine/physical_components.hpp
src/engine/physics_system.cpp
src/game_logic/ai/simple_walker.cpp
src/game_logic/ai/simple_walker.hpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp
src/ingame_mode.cpp

Walking turkey

---

src/game_logic/ai/blue_guard.hpp
src/game_logic/damage_components.hpp
src/game_logic/damage_infliction_system.cpp
src/game_logic/entity_configuration.ipp
src/game_logic/item_container.cpp
src/game_logic/item_container.hpp
src/game_logic/map_scroll_system.cpp
src/ingame_mode.cpp

Napalm bomb (red box trap)

---

src/CMakeLists.txt
src/data/map.cpp
src/data/map.hpp
src/engine/entity_tools.hpp
src/engine/physical_components.hpp
src/game_logic/ai/spike_ball.cpp
src/game_logic/damage_components.hpp
src/game_logic/damage_infliction_system.cpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp
src/game_logic/entity_factory.hpp
src/game_logic/ingame_systems.cpp
src/game_logic/ingame_systems.hpp
src/game_logic/player/projectile_system.cpp
src/game_logic/player/projectile_system.hpp

* Laser goes through walls and through enemies.
* Flame thrower goes through walls.
* Regular shots and rockets penetrate into walls before being destroyed,
which can sometimes kill/damage an enemy/item through a wall.
* Regular shots cause a small explosion/flame effect on hitting a wall.
* Rockets cause explosions when hitting things.
* All projectiles can damage multiple things at once, if those occupy
the same space
* Projectiles of any type are destroyed immediately when hitting a
destructible wall.
Closes #114 
Closes #74

Player weapons improvements

---

src/base/array_view.hpp
src/base/color.hpp
src/base/spatial_types.hpp
src/engine/renderer.cpp
src/game_logic/effect_components.hpp
src/game_main.cpp
src/ingame_mode.cpp

Raspberry Pi/Linux fixes

---

src/data/player_data.hpp
src/engine/rendering_system.cpp
src/game_logic/ai/red_bird.cpp
src/game_logic/ai/red_bird.hpp
src/game_session_mode.cpp
src/game_session_mode.hpp
src/ingame_mode.cpp
src/ingame_mode.hpp
src/loader/ega_image_decoder.cpp

Preserve player model between levels

---

src/CMakeLists.txt
src/engine/map_renderer.cpp
src/engine/map_renderer.hpp
src/engine/rendering_system.cpp
src/game_logic/damage_components.hpp
src/game_logic/damage_infliction_system.cpp
src/game_logic/damage_infliction_system.hpp
src/game_logic/dynamic_geometry_components.hpp
src/game_logic/dynamic_geometry_system.cpp
src/game_logic/dynamic_geometry_system.hpp
src/game_logic/entity_configuration.ipp
src/game_logic/ingame_systems.cpp
src/game_logic/ingame_systems.hpp

Wall debris

---

src/engine/map_renderer.cpp
src/engine/map_renderer.hpp
src/game_logic/dynamic_geometry_system.cpp

Fix wall debris

---

src/CMakeLists.txt
src/engine/earth_quake_effect.cpp
src/engine/renderer.cpp
src/engine/renderer.hpp
src/game_logic/ai/blue_guard.cpp
src/game_logic/ai/slime_blob.cpp
src/game_logic/destruction_effect_specs.ipp
src/game_logic/dynamic_geometry_system.cpp
src/game_logic/dynamic_geometry_system.hpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp
src/game_logic/ingame_systems.cpp
src/game_logic/ingame_systems.hpp
src/game_logic/interaction/force_field.cpp
src/game_logic/interaction/force_field.hpp
src/game_logic/item_container.hpp
src/game_main.cpp
src/game_runner.cpp
src/game_runner.hpp
src/game_session_mode.cpp
src/game_session_mode.hpp
src/global_level_events.hpp
src/ingame_mode.cpp
src/ingame_mode.hpp

Closes #234 
Closes #135 
Closes #155 
Closes #239 
#230 requires some more consideration, I'd like to see if there's a way to express the remaining ANDs differently as well.

Some visual effects, cleanups

---

src/game_logic/ai/blue_guard.cpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp

A few small things

---

src/data/player_data.hpp
src/game_logic/collectable_components.hpp
src/game_logic/entity_configuration.ipp
src/game_logic/ingame_systems.cpp
src/game_logic/player_interaction_system.cpp
src/game_logic/player_interaction_system.hpp

Score number effects for collected items, various fixes

---

src/CMakeLists.txt
src/data/player_data.cpp
src/data/player_data.hpp
src/game_logic/entity_configuration.ipp
src/game_logic/player_interaction_system.cpp
src/game_logic/player_interaction_system.hpp
test/CMakeLists.txt
test/test_letter_collection.cpp

Implements the 100000 points bonus when collecting the letters (`N`, `U`, `K`, `E`, `M`) in the right order.

Bonus letter collection bonus

---

src/game_main.cpp
src/game_main.ipp
src/game_mode.hpp
src/intro_demo_loop_mode.cpp
src/intro_demo_loop_mode.hpp
src/menu_mode.cpp
src/menu_mode.hpp
src/ui/duke_script_runner.cpp
src/ui/duke_script_runner.hpp

Persistent menu selections

---

src/CMakeLists.txt
src/data/player_model.cpp
src/data/player_model.hpp
src/data/strings.hpp
src/engine/sound_system.hpp
src/game_logic/ingame_systems.cpp
src/game_logic/player_interaction_system.cpp
src/game_logic/player_interaction_system.hpp
src/game_main.cpp
src/game_main.ipp
src/game_mode.hpp
src/game_runner.cpp
src/game_runner.hpp
src/game_session_mode.cpp
src/global_level_events.hpp
src/ui/ingame_message_display.cpp
src/ui/ingame_message_display.hpp
src/ui/menu_element_renderer.cpp
src/ui/menu_element_renderer.hpp
test/test_player_attack_system.cpp

Implement in-game message system, add a bunch of messages

---

src/CMakeLists.txt
src/data/player_model.cpp
src/data/player_model.hpp
src/engine/entity_tools.hpp
src/game_logic/ai/blue_guard.cpp
src/game_logic/entity_configuration.ipp
src/game_logic/ingame_systems.cpp
src/game_logic/ingame_systems.hpp
src/game_logic/interaction/respawn_checkpoint.cpp
src/game_logic/interaction/respawn_checkpoint.hpp
src/game_logic/player/components.hpp
src/game_logic/player_movement_system.cpp
src/game_logic/player_movement_system.hpp
src/game_runner.cpp
src/game_runner.hpp

Implement the checkpoint/respawn beacon

---

src/CMakeLists.txt
src/game_logic/enemy_radar.cpp
src/game_logic/enemy_radar.hpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp
src/game_logic/ingame_systems.cpp
src/game_logic/ingame_systems.hpp
src/game_runner.cpp
src/game_runner.hpp
src/game_session_mode.cpp

Radar dishes

---

src/engine/particle_system.cpp
src/game_logic/damage_components.hpp
src/game_logic/damage_infliction_system.cpp
src/game_logic/destruction_effect_specs.ipp
src/game_logic/effects_system.cpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp
src/game_logic/entity_factory.hpp
src/game_runner.cpp
src/game_runner.hpp

Various fixes and bits

---

CMakeLists.txt
src/base/warnings.hpp
src/engine/map_renderer.cpp
src/engine/map_renderer.hpp
src/engine/renderer.cpp
src/engine/rendering_system.cpp
src/engine/rendering_system.hpp
src/game_logic/actor_tag.hpp
src/game_logic/damage_components.hpp
src/game_logic/destruction_effect_specs.ipp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp
src/game_logic/ientity_factory.hpp
src/game_logic/ingame_systems.cpp
src/game_logic/ingame_systems.hpp
src/game_logic/player/projectile_system.cpp
src/game_runner.cpp
src/game_runner.hpp

Reactor destruction effects

---

CMakeLists.txt
src/CMakeLists.txt
src/data/game_session_data.hpp
src/data/level_hints.cpp
src/data/level_hints.hpp
src/game_logic/entity_configuration.ipp
src/game_logic/ingame_systems.cpp
src/game_logic/ingame_systems.hpp
src/game_logic/player/components.hpp
src/game_logic/player_interaction_system.cpp
src/game_logic/player_interaction_system.hpp
src/game_runner.cpp
src/game_runner.hpp
src/game_session_mode.cpp
src/loader/cmp_file_package.cpp
src/loader/cmp_file_package.hpp
src/loader/duke_script_loader.cpp
src/loader/resource_loader.cpp
src/ui/ingame_message_display.cpp
test/test_duke_script_loader.cpp

Implement hint machine

---

src/base/warnings.hpp
src/engine/renderer.cpp
src/engine/renderer.hpp
src/engine/rendering_system.cpp
src/engine/rendering_system.hpp
src/engine/shader.hpp
src/engine/texture.cpp
src/engine/texture.hpp
src/game_logic/actor_tag.hpp
src/game_logic/entity_configuration.ipp
src/game_runner.cpp
src/game_runner.hpp

Water effect

---

src/CMakeLists.txt
src/game_logic/behavior_controller.hpp
src/game_logic/behavior_controller_system.cpp
src/game_logic/behavior_controller_system.hpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp
src/game_logic/global_dependencies.hpp
src/game_logic/ingame_systems.cpp
src/game_logic/ingame_systems.hpp
src/game_logic/wind_blown_spiders_effect.cpp
src/game_logic/wind_blown_spiders_effect.hpp

Wind-blown spider effect

---

src/game_logic/ai/spider.cpp
src/game_logic/player.cpp
src/game_logic/player.hpp

Rapid fire for flame thrower

---

src/engine/entity_tools.hpp
src/engine/physics_system.cpp
src/engine/physics_system.hpp
src/engine/sprite_tools.hpp
src/game_logic/ai/slime_pipe.cpp
src/game_logic/ai/spider.cpp
src/game_logic/ai/spike_ball.cpp
test/test_physics_system.cpp
test/test_spike_ball.cpp

Correct gravity for non-player objects

---

src/CMakeLists.txt
src/data/player_model.cpp
src/data/player_model.hpp
src/game_logic/actor_tag.hpp
src/game_logic/dynamic_geometry_system.cpp
src/game_logic/dynamic_geometry_system.hpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp
src/game_logic/entity_factory.hpp
src/game_logic/interaction/force_field.cpp
src/game_logic/interaction/force_field.hpp
src/game_logic/interaction/locked_door.cpp
src/game_logic/interaction/locked_door.hpp
src/game_logic/player/components.hpp
src/game_logic/player_interaction_system.cpp
src/game_logic/player_interaction_system.hpp
src/global_level_events.hpp

Closes #80 
For now, the door simply disappears. Once #122 is done, the proper animation can be implemented.

Blue key door

---

src/CMakeLists.txt
src/game_logic/ai/ceiling_sucker.cpp
src/game_logic/ai/ceiling_sucker.hpp
src/game_logic/ai/spider.cpp
src/game_logic/ai/spider.hpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp
src/game_logic/player.cpp
src/game_logic/player.hpp

Ceiling sucker

---

.appveyor.yml
src/base/warnings.hpp
src/engine/imf_player.cpp
src/engine/physics_system.cpp
src/engine/physics_system.hpp
src/engine/renderer.cpp
src/game_logic/behavior_controller.hpp
src/game_logic/behavior_controller_system.cpp
src/game_logic/behavior_controller_system.hpp
src/game_logic/destruction_effect_specs.ipp
src/game_logic/effects_system.cpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp
src/game_logic/ingame_systems.cpp
src/game_logic/ingame_systems.hpp
src/game_logic/item_container.cpp
src/game_logic/item_container.hpp
src/game_logic/player_interaction_system.cpp
src/loader/cmp_file_package.cpp
test/test_duke_script_loader.cpp
test/test_letter_collection.cpp
test/test_main.cpp
test/test_physics_system.cpp
test/test_player.cpp
test/test_spike_ball.cpp

2-phase physics, better item container destruction

---

src/game_logic/destruction_effect_specs.ipp
src/game_logic/effect_components.hpp
src/game_logic/effects_system.cpp
src/game_logic/effects_system.hpp
src/game_logic/entity_configuration.ipp
src/game_logic/global_dependencies.hpp
src/game_logic/ingame_systems.cpp
src/game_logic/item_container.cpp
src/game_logic/player.cpp

Fix and extend soda can rocket

---

src/CMakeLists.txt
src/game_logic/ai/missile.cpp
src/game_logic/ai/missile.hpp
src/game_logic/destruction_effect_specs.ipp
src/game_logic/dynamic_geometry_system.cpp
src/game_logic/dynamic_geometry_system.hpp
src/game_logic/effects_system.cpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp
src/game_logic/entity_factory.hpp
src/game_logic/item_container.cpp
src/game_logic/player.cpp
src/game_logic/player/projectile_system.cpp
src/global_level_events.hpp

Implement missile

---

src/engine/debugging_system.cpp
src/engine/earth_quake_effect.cpp
src/engine/earth_quake_effect.hpp
src/game_logic/ai/ceiling_sucker.cpp
src/game_logic/ai/ceiling_sucker.hpp
src/game_logic/ai/laser_turret.cpp
src/game_logic/ai/missile.cpp
src/game_logic/ai/missile.hpp
src/game_logic/ai/slime_pipe.cpp
src/game_logic/ai/slime_pipe.hpp
src/game_logic/behavior_controller.hpp
src/game_logic/behavior_controller_system.cpp
src/game_logic/behavior_controller_system.hpp
src/game_logic/dynamic_geometry_components.hpp
src/game_logic/dynamic_geometry_system.cpp
src/game_logic/dynamic_geometry_system.hpp
src/game_logic/effect_actor_components.cpp
src/game_logic/effect_actor_components.hpp
src/game_logic/effects_system.cpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp
src/game_logic/entity_factory.hpp
src/game_logic/global_dependencies.hpp
src/game_logic/ingame_systems.cpp
src/game_logic/item_container.cpp
src/game_logic/item_container.hpp
src/game_logic/player/projectile_system.cpp
src/game_runner.cpp
src/game_runner.hpp
src/global_level_events.hpp

Implement dynamic geometry

---

src/CMakeLists.txt
src/base/spatial_types.hpp
src/game_logic/ai/bomber_plane.cpp
src/game_logic/ai/bomber_plane.hpp
src/game_logic/behavior_controller_system.cpp
src/game_logic/behavior_controller_system.hpp
src/game_logic/destruction_effect_specs.ipp
src/game_logic/dynamic_geometry_system.cpp
src/game_logic/effect_actor_components.cpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp
src/game_logic/global_dependencies.hpp

Bomber plane

---

src/CMakeLists.txt
src/engine/earth_quake_effect.cpp
src/engine/movement.cpp
src/game_logic/ai/bomber_plane.cpp
src/game_logic/ai/eyeball_thrower.cpp
src/game_logic/ai/eyeball_thrower.hpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp

Eyeball thrower

---

.travis.yml
CMakeLists.txt
src/base/math_tools.hpp
src/base/warnings.hpp
src/game_logic/entity_configuration.ipp

Migrate to C++ 17

---

src/game_logic/dynamic_geometry_system.cpp

Fix dynamic geometry

---

src/game_logic/ai/bomber_plane.cpp
src/game_logic/entity_configuration.ipp

Fix bomber plane

---

src/game_logic/ai/bomber_plane.cpp
src/game_logic/ai/bomber_plane.hpp
src/game_logic/ai/watch_bot.cpp
src/game_logic/ai/watch_bot.hpp

Fix: Prevent watch bot from getting stuck

---

src/CMakeLists.txt
src/engine/rendering_system.cpp
src/engine/visual_components.hpp
src/game_logic/ai/sliding_door.cpp
src/game_logic/ai/sliding_door.hpp
src/game_logic/ai/smash_hammer.cpp
src/game_logic/ai/smash_hammer.hpp
src/game_logic/behavior_controller.hpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp

Smash hammer

---

src/game_logic/destruction_effect_specs.ipp
src/game_logic/effect_actor_components.cpp
src/game_logic/effect_actor_components.hpp
src/game_logic/entity_configuration.ipp
src/game_runner.cpp
src/ui/ingame_message_display.cpp
src/ui/ingame_message_display.hpp

L1 explosion effect

---

src/CMakeLists.txt
src/data/bonus.hpp
src/game_logic/actor_tag.hpp
src/game_logic/entity_configuration.ipp
src/game_logic/ingame_systems.cpp
src/game_logic/item_container.cpp
src/game_logic/player/damage_system.cpp
src/game_logic/player/damage_system.hpp
src/game_logic/player_interaction_system.cpp
src/game_runner.cpp
src/game_runner.hpp
src/game_session_mode.cpp
src/global_level_events.hpp
src/ui/bonus_screen.cpp
src/ui/bonus_screen.hpp

Implement level-end bonuses

---

src/game_logic/ai/watch_bot.cpp
src/game_logic/ai/watch_bot.hpp
src/game_logic/entity_configuration.ipp

Implement watch bot carrier bot

---

src/engine/renderer.cpp

Fix blank screen issue

---

src/game_logic/ai/blue_guard.cpp
src/game_logic/ai/prisoner.cpp
src/game_logic/ai/watch_bot.cpp
src/game_logic/ingame_systems.cpp
src/game_logic/interaction/force_field.cpp
src/game_logic/player.cpp
src/game_logic/player.hpp
test/test_elevator.cpp
test/test_player.cpp

Jump salto

---

src/CMakeLists.txt
src/engine/debugging_system.cpp
src/engine/debugging_system.hpp
src/engine/entity_activation_system.cpp
src/engine/entity_activation_system.hpp
src/engine/map_renderer.cpp
src/engine/map_renderer.hpp
src/engine/particle_system.cpp
src/engine/particle_system.hpp
src/engine/rendering_system.cpp
src/engine/rendering_system.hpp
src/game_logic/ai/super_force_field.cpp
src/game_logic/camera.cpp
src/game_logic/camera.hpp
src/game_logic/ingame_systems.cpp
src/game_logic/ingame_systems.hpp
src/game_logic/map_scroll_system.cpp
src/game_logic/map_scroll_system.hpp
src/game_logic/player.cpp
src/game_logic/player.hpp
src/game_runner.cpp
src/game_runner.hpp
src/global_level_events.hpp

Improve camera

---

src/CMakeLists.txt
src/engine/entity_tools.hpp
src/game_logic/ai/floating_laser_bot.cpp
src/game_logic/ai/floating_laser_bot.hpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp

Floating laser bot

---

src/game_logic/camera.cpp
src/game_logic/player.cpp
src/game_logic/player.hpp

Flame thrower jetpack

---

src/CMakeLists.txt
src/data/game_session_data.hpp
src/data/unit_conversions.hpp
src/engine/tile_renderer.cpp
src/engine/tile_renderer.hpp
src/game_logic/ai/boss_episode_1.cpp
src/game_logic/ai/boss_episode_1.hpp
src/game_logic/destruction_effect_specs.ipp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp
src/game_main.cpp
src/game_main.ipp
src/game_mode.hpp
src/game_runner.cpp
src/game_runner.hpp
src/game_session_mode.cpp
src/game_session_mode.hpp
src/global_level_events.hpp
src/ui/bonus_screen.cpp
src/ui/bonus_screen.hpp
src/ui/duke_script_runner.cpp
src/ui/duke_script_runner.hpp
src/ui/episode_end_sequence.cpp
src/ui/episode_end_sequence.hpp
src/ui/hud_renderer.cpp
src/ui/hud_renderer.hpp
src/ui/menu_element_renderer.cpp
src/ui/menu_element_renderer.hpp

Episode 1 boss

---

src/CMakeLists.txt
src/data/high_score_list.cpp
src/data/high_score_list.hpp
src/game_main.cpp
src/game_main.ipp
src/game_mode.cpp
src/game_mode.hpp
src/game_runner.cpp
src/game_runner.hpp
src/game_session_mode.cpp
src/game_session_mode.hpp
src/loader/user_profile_import.cpp
src/loader/user_profile_import.hpp
src/menu_mode.cpp
src/menu_mode.hpp
src/ui/duke_script_runner.cpp
src/ui/duke_script_runner.hpp
src/ui/high_score_list.cpp
src/ui/high_score_list.hpp
src/ui/menu_element_renderer.cpp
src/ui/menu_element_renderer.hpp
src/ui/text_entry_widget.cpp
src/ui/text_entry_widget.hpp
src/user_profile.cpp
src/user_profile.hpp
test/CMakeLists.txt
test/test_high_score_list.cpp

This adds the high-score list to the user profile, and implements adding entries when leaving a game session.

Highscore list

---

src/game_logic/player.cpp

Fix assertion when dieing again after respawning at checkpoint

---

.appveyor.yml
README.md
cmake/Modules/FindSDL2.cmake
cmake/Modules/FindSDL2_mixer.cmake
src/CMakeLists.txt

Fix vcpkg build

---

.gitmodules
3rd_party/imgui/CMakeLists.txt
CMakeLists.txt
src/CMakeLists.txt
src/base/math_tools.hpp
src/common/game_service_provider.hpp
src/engine/sound_system.cpp
src/game_logic/enemies/boss_episode_1.cpp
src/game_logic/enemies/hover_bot.cpp
src/game_logic/enemies/slime_blob.cpp
src/game_logic/enemies/watch_bot.cpp
src/game_logic/game_world.cpp
src/game_logic/player/interaction_system.cpp
src/game_main.cpp
src/game_main.ipp
src/main.cpp
src/renderer/renderer.cpp
src/sdl_utils/error.hpp
src/ui/fps_display.cpp
src/ui/fps_display.hpp
src/ui/imgui_integration.cpp
src/ui/imgui_integration.hpp
src/ui/utils.cpp
src/ui/utils.hpp
test/utils.hpp

This will be used to implement the options menu.

Add Dear ImGui library + some cleanups

---

src/base/math_tools.hpp
src/game_logic/game_world.cpp
src/game_main.cpp
src/renderer/renderer.cpp
src/renderer/renderer.hpp
src/renderer/texture.cpp
src/renderer/texture.hpp

Refactor upscaling

---

src/game_logic/player/interaction_system.cpp
src/game_main.cpp
src/loader/actor_image_package.cpp
src/loader/actor_image_package.hpp
src/loader/audio_package.cpp
src/loader/audio_package.hpp
src/loader/cmp_file_package.cpp
src/loader/cmp_file_package.hpp
src/loader/file_utils.cpp
src/loader/file_utils.hpp
src/loader/level_loader.cpp
src/loader/resource_loader.cpp
src/loader/resource_loader.hpp
src/main.cpp
src/ui/duke_script_runner.cpp

Asset overrides

---

CMakeLists.txt
src/CMakeLists.txt
src/common/user_profile.cpp
src/common/user_profile.hpp
src/data/game_options.hpp
src/data/high_score_list.hpp
src/engine/imf_player.cpp
src/engine/imf_player.hpp
src/engine/sound_system.cpp
src/engine/sound_system.hpp
src/game_main.cpp
src/game_main.ipp
src/game_runner.cpp
src/game_runner.hpp
src/loader/adlib_emulator.hpp
src/loader/user_profile_import.cpp
src/loader/user_profile_import.hpp
src/main.cpp
src/menu_mode.cpp
src/menu_mode.hpp
src/renderer/renderer.cpp
src/ui/duke_script_runner.hpp
src/ui/imgui_integration.cpp
src/ui/imgui_integration.hpp
src/ui/options_menu.cpp
src/ui/options_menu.hpp

Introduce options menu

---

src/common/user_profile.cpp
src/common/user_profile.hpp
src/data/game_options.hpp
src/game_main.cpp
src/game_main.ipp
src/ui/options_menu.cpp

User profile versioning

---

src/common/user_profile.cpp
src/data/game_options.hpp
src/game_main.cpp
src/game_main.hpp
src/game_main.ipp
src/main.cpp
src/renderer/renderer.cpp
src/ui/options_menu.cpp

Contains some of the changes from #429. Since these are valuable improvements to the code, I'd like to merge these changes sooner, as #429 still needs a bit more work.

Preparations and refactoring

---

.travis.yml
src/CMakeLists.txt
src/common/json_utils.cpp
src/common/json_utils.hpp
src/common/user_profile.cpp
test/CMakeLists.txt
test/test_json_utils.cpp

Fix JSON merging

---

src/common/user_profile.cpp
src/data/game_options.hpp
src/game_main.cpp
src/game_main.ipp
src/ui/options_menu.cpp

Fps limit option

---

src/renderer/renderer.cpp

This was broken in 281019d94b9, because that commit changed the size
of the render target used by RenderingSystem to be as large as the
screen/window. This means the shader has to be adapted, but I forgot to
do this adaptation in the original commit.

Fix water effect rendering

---

src/common/json_utils.cpp
test/test_json_utils.cpp

Fix saving in levels L2 and up

---

src/CMakeLists.txt
src/game_logic/enemies/green_bird.cpp
src/game_logic/enemies/green_bird.hpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp

Implement green bird enemy

---

README.md
src/CMakeLists.txt
src/data/actor_ids.hpp
src/game_logic/enemies/flame_thrower_bot.cpp
src/game_logic/enemies/flame_thrower_bot.hpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp

Wall mounted flame thrower

---

src/CMakeLists.txt
src/data/sound_ids.hpp
src/engine/base_components.hpp
src/engine/entity_activation_system.cpp
src/game_logic/destruction_effect_specs.ipp
src/game_logic/enemies/flame_thrower_bot.cpp
src/game_logic/enemies/flame_thrower_bot.hpp
src/game_logic/enemies/small_flying_ship.cpp
src/game_logic/enemies/small_flying_ship.hpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp
src/game_logic/global_dependencies.hpp
src/game_logic/hazards/lava_fountain.cpp
src/game_logic/hazards/lava_fountain.hpp

More registered version enemies

---

README.md
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.hpp
src/game_logic/player.cpp
src/game_logic/player.hpp
src/game_logic/player/projectile_system.cpp
test/test_player.cpp

Couple of fixes

---

README.md
src/CMakeLists.txt
src/base/math_tools.hpp
src/common/global.hpp
src/engine/movement.cpp
src/game_logic/enemies/big_green_cat.hpp
src/game_logic/enemies/boss_episode_1.cpp
src/game_logic/enemies/boss_episode_1.hpp
src/game_logic/enemies/boss_episode_3.cpp
src/game_logic/enemies/boss_episode_3.hpp
src/game_logic/enemies/boss_episode_4.cpp
src/game_logic/enemies/boss_episode_4.hpp
src/game_logic/enemies/dying_boss.cpp
src/game_logic/enemies/dying_boss.hpp
src/game_logic/enemies/flame_thrower_bot.hpp
src/game_logic/enemies/grabber_claw.hpp
src/game_logic/enemies/green_bird.hpp
src/game_logic/enemies/small_flying_ship.hpp
src/game_logic/enemies/spiked_green_creature.hpp
src/game_logic/enemies/unicycle_bot.hpp
src/game_logic/enemies/wall_walker.hpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp
src/game_logic/game_world.cpp
src/game_logic/game_world.hpp
src/game_logic/hazards/lava_fountain.hpp
src/game_logic/ientity_factory.hpp
src/game_logic/player.cpp

Closes #349 
Closes #350 
The boss for episode 2 has more complicated logic, and will be done separately.
Also includes a bunch of fixes for issues I discovered while testing the new bosses.

Implement 2 of 3 registered version bosses

---

src/CMakeLists.txt
src/game_logic/enemies/boss_episode_2.cpp
src/game_logic/enemies/boss_episode_2.hpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp

Implement episode 2 boss

---

src/game_logic/player.cpp
test/test_player.cpp

Fix jumping off climbable pipe

---

src/game_logic/enemies/boss_episode_2.hpp
src/game_logic/enemies/spiked_green_creature.hpp
src/game_logic/enemies/unicycle_bot.hpp
src/game_logic/hazards/lava_fountain.cpp
src/game_logic/hazards/lava_fountain.hpp

Fix building with Gcc 9

---

AUTHORS.md
README.md

@mnhauke FYI - thanks again for making the package! :penguin:

Add link to OpenSUSE package

---

src/data/tile_attributes.hpp
src/data/tile_attributes.ipp
src/engine/collision_checker.cpp
src/engine/collision_checker.hpp
src/game_logic/dynamic_geometry_system.cpp
src/game_logic/ingame_systems.cpp
src/game_logic/player/projectile_system.cpp
src/game_logic/player/projectile_system.hpp

Fix player shot and dynamic geometry collision checking

---

src/CMakeLists.txt
src/engine/life_time_system.cpp
src/game_logic/enemies/enemy_rocket.cpp
src/game_logic/enemies/enemy_rocket.hpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp
src/game_logic/player.cpp
src/game_logic/player.hpp
src/game_logic/player/damage_system.cpp

Fix enemy rocket

---

src/game_main.cpp
src/game_main.ipp
src/game_runner.cpp
src/game_runner.hpp

Improve controller support

---

src/game_logic/player.cpp
src/game_logic/player/components.hpp

Fix climbing attachment and collision

---

src/game_logic/entity_configuration.ipp
src/game_logic/ingame_systems.cpp
src/game_logic/interactive/item_container.cpp
src/game_logic/interactive/item_container.hpp

Make item container release sequence match the original

---

README.md

Add section about installing dependencies on Fedora/other distros

---

src/game_logic/interactive/blowing_fan.cpp
src/game_logic/player.cpp

Make blowing fan consistent with original

---

src/base/math_tools.hpp
src/game_runner.cpp
src/ui/duke_script_runner.cpp
src/ui/duke_script_runner.hpp

Controller support improvements

---

README.md

And remove some instructions which aren't relevant anymore for the new download link.
Closes #529

Update link to shareware download

---

src/game_logic/camera.cpp
src/game_logic/enemies/red_bird.cpp
src/game_logic/enemies/red_bird.hpp
src/game_logic/game_world.cpp
src/game_logic/player.cpp

Fixes #354 
Fixes #528
Fixes #535

More bug fixes

---

README.md

Update link to showcase video

---

src/game_logic/entity_configuration.ipp

Fix living turkey animation

---

src/menu_mode.cpp

Fix main menu still receiving input when options menu active

---

src/CMakeLists.txt
src/base/defer.hpp
src/common/user_profile.cpp
src/common/user_profile.hpp
src/game_main.cpp
src/game_main.hpp
src/game_main.ipp
src/platform.cpp
src/platform.hpp
src/ui/game_path_browser.cpp
src/ui/game_path_browser.hpp

Restructures the code so that an Emscripten main loop can be added cleanly, as discussed in #531 .

Prepare Wasm port

---

src/data/sound_ids.hpp
src/engine/sound_system.cpp
src/engine/sound_system.hpp
src/game_main.cpp
src/game_main.ipp
src/renderer/renderer.cpp

Fix Webassembly audio

---

src/renderer/renderer.cpp

Fix visual glitches on Odroid Go Advance

---

src/game_logic/game_world.cpp
src/game_logic/player/interaction_system.cpp

Fix newly found bugs

---

README.md

Add a note about Duke 1 and Cosmo to README

---

src/menu_mode.cpp
src/ui/duke_script_runner.cpp
src/ui/duke_script_runner.hpp
src/ui/ingame_menu.cpp

Some menu features/improvements

---

3rd_party/nlohmann/nlohmann/json.hpp

Update JSON library to latest master

---

.github/workflows/ci.yml
.travis.yml
3rd_party/CMakeLists.txt
3rd_party/dbopl/CMakeLists.txt
3rd_party/glad/CMakeLists.txt
3rd_party/imgui/CMakeLists.txt
3rd_party/speex_resampler/CMakeLists.txt
CMakeLists.txt
README.md
cmake/rigel.cmake
src/CMakeLists.txt
test/CMakeLists.txt

CMake cleanups

---

src/CMakeLists.txt
src/data/actor_ids.hpp
src/game_runner.cpp
src/game_runner.hpp
src/game_session_mode.cpp
src/ui/bonus_screen.cpp
src/ui/duke_3d_teaser_screen.cpp
src/ui/duke_3d_teaser_screen.hpp
src/ui/episode_end_sequence.cpp
src/ui/episode_end_sequence.hpp
src/ui/movie_player.cpp
src/ui/movie_player.hpp

Add Duke 3D teaser screen after episode 4

---

src/game_logic/player.cpp

Fix draw order for Duke's ship

---

src/common/user_profile.cpp
src/data/game_options.hpp
src/engine/sprite_factory.cpp
src/game_logic/demo_player.cpp
src/game_logic/demo_player.hpp
src/game_logic/enemies/blue_guard.cpp
src/game_logic/enemies/boss_episode_3.cpp
src/game_logic/enemies/floating_laser_bot.cpp
src/game_logic/enemies/laser_turret.cpp
src/game_logic/enemies/rocket_turret.cpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp
src/game_logic/entity_factory.hpp
src/game_logic/game_world.cpp
src/game_logic/game_world.hpp
src/game_logic/ientity_factory.hpp
src/game_logic/player.cpp
src/game_logic/player.hpp
src/game_logic/player/projectile_system.cpp
src/game_logic/world_state.cpp
src/game_logic/world_state.hpp
src/ui/options_menu.cpp
test/test_elevator.cpp
test/test_player.cpp
test/test_spike_ball.cpp

More work on demo parity, introducing compatibility mode

---

.github/workflows/ci.yml
README.md
src/loader/audio_package.cpp
src/loader/file_utils.cpp
src/loader/level_loader.cpp
src/renderer/shader.hpp

Fix 32-bit Windows build, improve build instructions

---

src/data/player_model.cpp
src/data/player_model.hpp
src/game_logic/collectable_components.hpp
src/game_logic/entity_configuration.ipp
src/game_logic/game_world.cpp
src/game_logic/game_world.hpp
src/game_logic/world_state.cpp
src/ui/ingame_menu.cpp
src/ui/ingame_menu.hpp

Implement cheat codes

---

src/engine/sprite_rendering_system.cpp
src/engine/visual_components.hpp
src/game_logic/enemies/grabber_claw.cpp
src/game_logic/enemies/grabber_claw.hpp
src/game_logic/entity_configuration.ipp
src/game_logic/game_world.cpp
src/game_logic/game_world.hpp
src/game_logic/hazards/lava_fountain.cpp
src/game_logic/hazards/lava_fountain.hpp
src/game_logic/hazards/smash_hammer.cpp
src/game_logic/hazards/smash_hammer.hpp
src/game_logic/interactive/sliding_door.cpp
src/game_logic/interactive/sliding_door.hpp
src/game_logic/world_state.cpp
src/renderer/renderer.cpp
src/renderer/renderer.hpp

Todo: Delete unused `drawSpriteFrame` function

More rendering improvements

---

src/common/global.hpp
src/data/player_model.cpp
src/game_logic/player.cpp
src/game_logic/player.hpp
src/game_logic/player/interaction_system.cpp

Fix cloak/rapid fire re-pick up behavior

---

src/renderer/renderer.cpp
src/renderer/renderer.hpp

Fix water effect shader artifacts on Raspberry Pi

---

3rd_party/imgui/CMakeLists.txt
3rd_party/imgui/imgui_impl_opengl3.cpp
3rd_party/imgui/imgui_impl_sdl.cpp

Fix mouse interaction on Raspberry Pi

---

src/game_main.cpp

Relaunch path setup if path is invalid

---

src/renderer/renderer.cpp
src/ui/duke_script_runner.cpp
src/ui/ingame_menu.cpp
src/ui/menu_navigation.cpp
src/ui/menu_navigation.hpp
src/ui/movie_player.cpp

More fixes

---

.github/workflows/ci.yml

Wasm: Publish artifact from action

---

emscripten/shell.html
src/frontend/game.cpp

Some progress on #652, although the styling could still be much better.

Better welcome box

---

emscripten/shell.html

Adjust welcome box link colors

---

src/renderer/renderer.cpp

Make water shader work reliably in wasm version

---

.dockerignore
.github/workflows/ci.yml
BUILDING.md
cmake/Modules/FindFilesystem.cmake
docker/ubuntu-deps.sh
docker/ubuntu.Dockerfile

Dockerfile + instructions on how to build/run in docker.

Add ubuntu latest dockerfile

---

CMakeLists.txt
src/CMakeLists.txt
test/CMakeLists.txt

Hello,
These are small things that have been bugging me while working through the other issues.
As usual I may have missed something... 
Cheers!

Cmake minor fixes

---

src/renderer/renderer.cpp

Fix backdrop flash effect

---

src/engine/sound_system.cpp
src/engine/sound_system.hpp
src/frontend/game.cpp
src/loader/resource_loader.cpp
src/loader/resource_loader.hpp
src/sdl_utils/ptr.hpp

Makes it possible to replace sound effects with wave files, and music with mp3/ogg/flac/wave/modules.

Implement sound & music modding

---

src/engine/sound_system.cpp

Gracefully handle non-existing asset_replacements dir

---

src/engine/sound_system.cpp
src/engine/sound_system.hpp

Always open audio device in stereo

---

src/CMakeLists.txt

See https://bugs.chromium.org/p/v8/issues/detail?id=11863
Closes #690

Work around v8 bug in mobile Chrome

---

src/game_logic/game_world.cpp
src/game_logic/game_world.hpp

Fix widescreen culling

---

src/base/defer.hpp
src/common/game_service_provider.hpp
src/common/user_profile.cpp
src/data/game_options.hpp
src/data/sound_ids.hpp
src/engine/sound_system.cpp
src/engine/sound_system.hpp
src/frontend/game.cpp
src/frontend/game.hpp
src/frontend/intro_demo_loop_mode.cpp
src/game_main.cpp
src/loader/resource_loader.cpp
src/loader/resource_loader.hpp
src/ui/options_menu.cpp
src/ui/utils.cpp
src/ui/utils.hpp
test/utils.hpp

Add sound style option

---

src/common/user_profile.cpp
src/data/game_options.hpp
src/frontend/game.cpp
src/frontend/game.hpp
src/game_logic/camera.cpp
src/game_logic/game_world.cpp
src/game_logic/game_world.hpp
src/ui/options_menu.cpp

Closes #708 
Fixes #699
Fixes #710

Add screen flash option and fix bugs

---

src/platform.cpp
src/renderer/renderer.cpp
src/ui/imgui_integration.cpp

Implement high DPI support on Mac

---

src/game_logic/enemies/dying_boss.cpp
src/game_logic/enemies/dying_boss.hpp
src/game_logic/enemies/spider.cpp
src/game_logic/entity_configuration.ipp
src/game_logic/game_world.cpp
src/game_logic/player.cpp
src/game_logic/player/interaction_system.cpp
src/game_logic/world_state.cpp
src/game_logic/world_state.hpp

Fixes #719 
Fixes #713 
Fixes #715 
Fixes #714 
Also adds a small enhancement: The boss health bar in N8 is now proportional.

Various bug fixes

---

cmake/rigel.cmake
src/main.cpp

Ignore all command line args if the exe has been renamed

---

src/game_logic/enemies/snake.cpp
src/game_logic/enemies/snake.hpp

Fix softlock when killing snake right before being incapacitated

---

src/ui/menu_navigation.cpp

Numpad arrow keys

---

src/frontend/game.cpp

Fix alt-tabbing on Linux

---

src/game_logic/behavior_controller.hpp
src/game_logic/behavior_controller_system.cpp
src/game_logic/damage_components.hpp
src/game_logic/damage_infliction_system.cpp
src/game_logic/enemies/blue_guard.cpp
src/game_logic/enemies/blue_guard.hpp
src/game_logic/enemies/laser_turret.cpp
src/game_logic/enemies/laser_turret.hpp
src/game_logic/enemies/spike_ball.cpp
src/game_logic/enemies/spike_ball.hpp
src/game_logic/entity_configuration.ipp
src/game_logic/interactive/super_force_field.cpp
src/game_logic/interactive/super_force_field.hpp

Fix firebomb not destroying laser turret

---

BUILDING.md
src/frontend/game.cpp
src/frontend/game.hpp
src/game_logic/game_world.cpp
src/game_logic/game_world.hpp
src/renderer/renderer.cpp
src/renderer/upscaling_utils.cpp
src/ui/options_menu.cpp

Fix Mac high DPI rendering when modded

---

src/game_logic/world_state.cpp

Fix laser turret being destructible with regular shot after quick load

---

src/game_logic/player.cpp
src/game_logic/player.hpp

Fix the wall dancing glitch. Sorry Bart! 😉 

---

cmake/rigel.cmake
src/data/image.cpp
src/data/image.hpp
src/engine/map_renderer.cpp
src/frontend/game.cpp
src/frontend/game.hpp
src/renderer/renderer.cpp
src/renderer/renderer.hpp

Add screenshot function

---

src/base/array_view.hpp
test/CMakeLists.txt
test/test_array_view.cpp

Hey,
So sorry, somehow I messed up my other MR.
I did take all of your comments into consideration!
GIST:
* CTAD
* tests
* remove unused headers
* more constexpr
* more [[nodiscard]]

Minor improvements to ArrayView

---

src/data/game_traits.hpp
src/game_logic/destruction_effect_specs.ipp
src/game_logic/effects_system.cpp
src/game_logic/enemies/bomber_plane.cpp
src/game_logic/enemies/dying_boss.cpp
src/game_logic/enemies/prisoner.cpp
src/game_logic/game_world.cpp
src/game_logic/interactive/missile.cpp
src/game_logic/interactive/super_force_field.cpp
src/game_logic/player.cpp
src/loader/actor_image_package.hpp
src/loader/palette.cpp
src/loader/palette.hpp
src/loader/resource_loader.cpp
src/renderer/renderer.cpp
src/ui/duke_script_runner.cpp
src/ui/hud_renderer.cpp

Move INGAME_PALETTE constant to data package

---

src/CMakeLists.txt
src/base/spatial_types.hpp
src/common/user_profile.cpp
src/data/game_options.hpp
src/engine/base_components.hpp
src/engine/map_renderer.cpp
src/engine/map_renderer.hpp
src/engine/motion_smoothing.hpp
src/engine/particle_system.cpp
src/engine/particle_system.hpp
src/engine/sprite_rendering_system.cpp
src/engine/sprite_rendering_system.hpp
src/engine/tiled_texture.cpp
src/engine/tiled_texture.hpp
src/frontend/game_runner.cpp
src/game_logic/debugging_system.cpp
src/game_logic/debugging_system.hpp
src/game_logic/dynamic_geometry_system.cpp
src/game_logic/enemies/spider.cpp
src/game_logic/entity_configuration.ipp
src/game_logic/entity_factory.cpp
src/game_logic/game_world.cpp
src/game_logic/game_world.hpp
src/game_logic/hazards/slime_pipe.cpp
src/game_logic/interactive/item_container.cpp
src/game_logic/player.cpp
src/game_logic/player/components.hpp
src/game_logic/world_state.cpp
src/game_logic/world_state.hpp
src/ui/options_menu.cpp

Smooth motion 4real

---

src/common/game_service_provider.hpp
src/data/game_traits.hpp
src/data/palette.hpp
src/engine/map_renderer.cpp
src/frontend/game.cpp
src/frontend/game.hpp
src/game_logic/player.cpp
src/loader/actor_image_package.cpp
src/loader/actor_image_package.hpp
src/loader/ega_image_decoder.cpp
src/loader/ega_image_decoder.hpp
src/loader/movie_loader.cpp
src/loader/palette.cpp
src/loader/png_image.cpp
src/loader/png_image.hpp
src/loader/resource_loader.cpp
src/loader/resource_loader.hpp
src/ui/duke_3d_teaser_screen.cpp
src/ui/duke_script_runner.cpp
src/ui/duke_script_runner.hpp
src/ui/ingame_menu.hpp
src/ui/options_menu.cpp
src/ui/utils.cpp
src/ui/utils.hpp
test/utils.hpp

Release preparations

---

src/CMakeLists.txt
src/audio/imf_player.cpp
src/audio/imf_player.hpp
src/audio/sound_system.cpp
src/audio/sound_system.hpp
src/frontend/game.cpp
src/frontend/game.hpp

Move audio-related code into dedicated "audio" package

---

src/game_logic/enemies/boss_episode_1.cpp
src/game_logic/enemies/boss_episode_1.hpp
src/game_logic/enemies/ceiling_sucker.cpp
src/game_logic/enemies/ceiling_sucker.hpp
src/game_logic/enemies/eyeball_thrower.cpp
src/game_logic/enemies/eyeball_thrower.hpp
src/game_logic/enemies/floating_laser_bot.cpp
src/game_logic/enemies/floating_laser_bot.hpp
src/game_logic/enemies/rigelatin_soldier.cpp
src/game_logic/enemies/rigelatin_soldier.hpp
src/game_logic/enemies/snake.cpp
src/game_logic/enemies/snake.hpp
src/game_logic/enemies/watch_bot.cpp
src/game_logic/enemies/watch_bot.hpp
src/game_logic/hazards/smash_hammer.cpp
src/game_logic/hazards/smash_hammer.hpp

Move state structs into behavior classes

---

src/frontend/intro_demo_loop_mode.cpp

Make intro movie files optional

---

src/CMakeLists.txt
src/audio/software_imf_player.cpp
src/audio/software_imf_player.hpp
src/audio/sound_system.cpp
src/audio/sound_system.hpp
src/base/array_view.cpp
src/base/array_view.hpp
src/frontend/intro_demo_loop_mode.cpp
src/game_logic/camera.cpp
src/game_logic/camera.hpp
src/game_logic/game_world.cpp
src/ui/duke_script_runner.cpp
src/ui/intro_movie.cpp
src/ui/movie_player.cpp
src/ui/options_menu.cpp
test/test_array_view.cpp

Fixes #787 
Fixes #785 
Fixes #786

Cleanups and fixes

---

3rd_party/CMakeLists.txt
3rd_party/nuked-opl3/CMakeLists.txt
3rd_party/nuked-opl3/LICENSE
3rd_party/nuked-opl3/opl3.c
3rd_party/nuked-opl3/opl3.h
src/CMakeLists.txt
src/audio/adlib_emulator.hpp
src/audio/software_imf_player.cpp
src/audio/software_imf_player.hpp
src/audio/sound_system.cpp
src/audio/sound_system.hpp
src/common/user_profile.cpp
src/data/game_options.hpp
src/frontend/game.cpp
src/loader/adlib_emulator.hpp
src/loader/audio_package.cpp
src/loader/audio_package.hpp
src/loader/resource_loader.cpp
src/loader/resource_loader.hpp
src/ui/options_menu.cpp

Add Nuked OPL3 for music playback

---

cmake/rigel.cmake
src/game_logic/enemies/ceiling_sucker.cpp
src/game_logic/enemies/ceiling_sucker.hpp
src/game_logic/player.cpp
src/game_logic/player.hpp

Fix gamebreaking bugs

---

src/audio/adlib_emulator.hpp
src/audio/sound_system.cpp
src/loader/voc_decoder.cpp
src/ui/options_menu.cpp
src/ui/options_menu.hpp

Fixes #797 
Some progress regarding #6

Better sound quality

---

src/engine/map_renderer.cpp
src/renderer/upscaling_utils.cpp

Release prep 0.8.3

---

src/renderer/upscaling_utils.cpp

Scaling fixes

---

src/renderer/shader_code.cpp

Fix visual glitches on OGA/OGS

---

src/game_logic/game_world.cpp

Fix broken fade-in when using teleporter

---

src/data/game_traits.hpp
src/engine/base_components.hpp
src/engine/entity_activation_system.cpp
src/engine/entity_activation_system.hpp
src/engine/life_time_system.cpp
src/engine/life_time_system.hpp
src/engine/map_renderer.cpp
src/engine/map_renderer.hpp
src/engine/sprite_rendering_system.cpp
src/engine/sprite_rendering_system.hpp
src/frontend/game.cpp
src/game_logic/camera.cpp
src/game_logic/camera.hpp
src/game_logic/debugging_system.cpp
src/game_logic/debugging_system.hpp
src/game_logic/effect_actor_components.cpp
src/game_logic/game_world.cpp
src/game_logic/game_world.hpp
src/game_logic/global_dependencies.hpp
src/loader/resource_loader.cpp
src/renderer/upscaling_utils.cpp
src/renderer/upscaling_utils.hpp
src/ui/duke_script_runner.cpp
src/ui/hud_renderer.cpp
src/ui/movie_player.cpp
test/test_elevator.cpp
test/test_spike_ball.cpp

Made Viewport consistent throughout

---

docker/ubuntu.Dockerfile

I noticed there were some unnecessary image layers so I removed those. Also, removed the stage tag as we don't have multiple stages.

Optimising Ubuntu Dockerfile

---

src/assets/voc_decoder.cpp
src/ui/options_menu.cpp

Getting very close to having #6 done.

Even better ADPCM decoding

---

src/CMakeLists.txt
src/engine/graphical_effects.cpp
src/engine/graphical_effects.hpp
src/game_logic/game_world.cpp
src/game_logic/game_world.hpp
src/renderer/custom_quad_batch.hpp
src/renderer/renderer.cpp
src/renderer/renderer.hpp
src/renderer/renderer_support.hpp
src/renderer/shader.cpp
src/renderer/shader.hpp
src/renderer/shader_code.cpp
src/renderer/shader_code.hpp
src/renderer/vertex_buffer_utils.hpp

TODO
* ~Instead of friend decl, pass a struct `CustomQuadBatchData` to renderer. Add function to `CustomQuadBatch` class to generate that struct.~
* ~Add clear function to `CustomQuadBatch`.~
* ~rework the state reset after custom draw so that it let's the next draw operation recommit shader & transform~
* ~Reuse single batch builder instance in water effect renderer, to minimize allocations~
* ~Fix the texture repeat issue~

Shader refactoring

---

docker/ubuntu.Dockerfile
tools/format-staged.sh

Create Shell script which runs clang-format on all staged files

---

src/game_logic/camera.cpp
src/game_logic/camera.hpp
src/game_logic/game_world.cpp
src/renderer/upscaling_utils.cpp
src/ui/hud_renderer.hpp

Revert widescreen camera

---

src/data/game_options.hpp
src/frontend/game.cpp
src/frontend/game.hpp
src/frontend/menu_mode.cpp
src/frontend/user_profile.cpp
src/renderer/custom_quad_batch.hpp
src/renderer/renderer.cpp
src/renderer/shader.cpp
src/renderer/shader.hpp
src/renderer/shader_code.cpp
src/renderer/shader_code.hpp
src/renderer/texture.cpp
src/renderer/texture.hpp
src/renderer/upscaling_utils.cpp
src/renderer/upscaling_utils.hpp
src/ui/ingame_menu.cpp
src/ui/options_menu.cpp
src/ui/options_menu.hpp

Most of #720 
TODO:
* ~Investigate single-pass sharp bilinear option~
* Add hybrid option: pixel-perfect X + sharp bilinear Y

Scaling options

---

3rd_party/CMakeLists.txt
3rd_party/loguru/CMakeLists.txt
3rd_party/loguru/loguru.cpp
3rd_party/loguru/loguru.hpp
src/CMakeLists.txt
src/audio/sound_system.cpp
src/data/game_options.cpp
src/data/game_options.hpp
src/data/mod_library.cpp
src/frontend/game.cpp
src/frontend/user_profile.cpp
src/game_logic/game_world.cpp
src/game_main.cpp
src/main.cpp
src/platform.cpp
src/renderer/opengl.hpp
src/ui/options_menu.cpp

Add logging

---

3rd_party/imgui-filebrowser/imfilebrowser.cpp
src/assets/cmp_file_package.cpp
src/assets/cmp_file_package.hpp
src/assets/file_utils.cpp
src/assets/file_utils.hpp
src/assets/resource_loader.cpp
src/frontend/game.cpp

Fix non-ASCII game paths

---

src/game_logic/dynamic_geometry_system.cpp
src/game_logic/dynamic_geometry_system.hpp

Fix dynamic geometry being drawn when it shouldn't

---

dist/linux/rigelengine.metainfo.xml
src/frontend/input_handler.cpp
src/frontend/input_handler.hpp
src/ui/ingame_menu.cpp
src/ui/ingame_menu.hpp
src/ui/options_menu.cpp

Better gamepad controls

---

src/data/game_options.hpp
src/frontend/game.cpp
src/frontend/user_profile.cpp
src/renderer/upscaling.cpp
src/renderer/upscaling.hpp
src/ui/options_menu.cpp

Add option to disable aspect ratio correction in pixel-perfect mode

---

src/engine/map_renderer.cpp
src/game_logic/damage_infliction_system.cpp
src/game_logic/game_world.cpp
src/game_logic/game_world.hpp
src/game_logic/global_dependencies.hpp
src/game_logic/player.cpp
src/game_logic/player/interaction_system.cpp
src/ui/ingame_message_display.cpp
src/ui/ingame_message_display.hpp

Improve parity

---

src/assets/duke_script_loader.cpp
src/data/duke_script.hpp
src/ui/duke_script_runner.cpp
src/ui/duke_script_runner.hpp
src/ui/menu_element_renderer.cpp
src/ui/menu_element_renderer.hpp
test/test_duke_script_loader.cpp

Message box anim

---

src/game_logic/enemies/watch_bot.cpp
src/game_logic/enemies/watch_bot.hpp
src/game_logic/entity_configuration.ipp
src/ui/ingame_menu.cpp

Bits and bobs

---

.github/workflows/bundling.yml

Disable Mac bundling for now

---

src/game_logic/collectable_components.hpp
src/game_logic/damage_components.hpp
src/game_logic/damage_infliction_system.cpp
src/game_logic/dynamic_geometry_components.hpp
src/game_logic/dynamic_geometry_system.cpp
src/game_logic/dynamic_geometry_system.hpp
src/game_logic/entity_configuration.ipp
src/game_logic/game_world.cpp
src/game_logic/player/interaction_system.cpp
src/game_logic/world_state.cpp

More parity stuff

---

src/assets/file_utils.cpp
src/frontend/user_profile.cpp

Fix saving user profile in non-ASCII paths

---

3rd_party/loguru/loguru.cpp
src/assets/file_utils.cpp
src/assets/file_utils.hpp
src/assets/png_image.cpp
src/assets/png_image.hpp
src/assets/resource_loader.cpp
src/data/mod_library.cpp
src/frontend/game.cpp
src/frontend/user_profile.cpp

Fix more non-ASCII path issues

---

.github/workflows/bundling.yml

Re-enable Mac bundling

---

.github/workflows/ci.yml
src/engine/movement.cpp
src/engine/movement.hpp
src/frontend/game_runner.cpp
src/game_logic/camera.cpp
src/game_logic/enemies/big_green_cat.cpp
src/game_logic/enemies/spiked_green_creature.cpp
src/game_logic/enemies/spiked_green_creature.hpp
src/game_logic/enemies/wall_walker.cpp
src/game_logic/entity_configuration.ipp
src/game_logic/game_world.cpp
src/game_logic/world_state.cpp

Fixes #901
Fixes #899
Fixes #898

Tons of parity fixes

---

src/frontend/user_profile.cpp
src/frontend/user_profile.hpp
src/main.cpp

Implement a "portable" mode

---

3rd_party/imgui-filebrowser/imfilebrowser.cpp

Hi,
great port :)
WebAssembly compile errored in a file with latest Emscripten, so I've fixed it.
Have a nice weekend
midzer

fix Emscripten build
