- src/CMakeLists.txt
- src/base/boost_variant.hpp
- src/base/spatial_types.hpp
- src/data/duke_script.hpp
- src/engine/physics_system.cpp
- src/engine/physics_system.hpp
- src/game.cpp
- src/game_logic/entity_configuration.ipp
- src/game_logic/entity_factory.cpp
- src/game_logic/trigger_components.hpp
- src/game_session_mode.cpp
- src/game_session_mode.hpp
- src/ingame_mode.cpp
- src/ingame_mode.hpp
- src/loader/level_loader.cpp
- src/ui/bonus_screen.cpp
- src/ui/bonus_screen.hpp
Implements level exit triggers, integrates the bonus screen and makes it possible to transition to the next level upon reaching the exit. Many levels can currently not be finished due to missing player
movement (e.g. hanging on poles) or entities (e.g. rocket elevator), but it's already possible for some, e.g. L3 and L6.
Closes #15 and #44
> Level exits

- src/data/player_data.hpp
- src/engine/physics_system.cpp
- src/game_logic/entity_configuration.ipp
- src/game_logic/entity_factory.cpp
- src/game_logic/entity_factory.hpp
- src/game_logic/player/attack_system.cpp
- src/game_logic/player/attack_system.hpp
- src/game_logic/player_interaction_system.cpp
- src/ingame_mode.cpp
- test/test_player_attack_system.cpp
Adds support for the different player weapons (laser, flame thrower, rocket launcher). The player's shots now have the correct sound, sprite, and damage multiplier according to the currently carried weapon. The non-regular weapons use ammo, and are reset back to the normal weapon when they are depleted.
Still missing at this point:
- always rapid fire for flame thrower
- laser going through enemies/walls
- flame thrower going through walls?? Not entirely clear yet, but seems like that's the case in the original game
- downwards shot (jetpack) for flame thrower
- weird projectile positioning for left-facing shots as found in the original game
It's also worth noting that the original game doesn't show ammo consumption correctly for the flame thrower. The flame thrower has twice as much ammo …
> Add different weapon types for player

- src/CMakeLists.txt
- src/data/map.cpp
- src/data/map.hpp
- src/engine/physics_system.cpp
- src/engine/physics_system.hpp
- src/game_logic/damage_infliction_system.cpp
- src/game_logic/damage_infliction_system.hpp
- src/game_logic/dynamic_geometry_components.hpp
- src/game_logic/entity_configuration.ipp
- src/game_logic/entity_factory.cpp
- src/game_logic/entity_factory.hpp
- src/ingame_mode.cpp
Implements shootable walls, like they are found in the very first level (L1). As a side-effect, all dynamic geometry is now part of the level, even if its behavior isn't implemented yet. This means the exit isn't reachable anymore in some levels, where it could only be reached because dynamic geometry like doors was being removed. This is not really a big deal though, since we want to focus on getting L1 playable first, and there is no dynamic geometry besides shootable walls in that level.
Closes #32
> Shootable walls

- src/CMakeLists.txt
- src/data/player_data.hpp
- src/game_logic/entity_configuration.ipp
- src/game_logic/entity_factory.cpp
- src/game_logic/interaction/force_field.cpp
- src/game_logic/interaction/force_field.hpp
- src/game_logic/player/components.hpp
- src/game_logic/player_interaction_system.cpp
This implements disabling the force field if the player is carrying the key-card (circuit board). It's functional, but there are still some parts missing: The player doesn't show the "interacting" animation, the message ("Access granted") is not displayed, and the player isn't temporarily locked in position.
Closes #30
> Key-card force field

- src/CMakeLists.txt
- src/engine/base_components.hpp
- src/engine/entity_activation_system.cpp
- src/engine/entity_activation_system.hpp
- src/engine/life_time_components.hpp
- src/engine/life_time_system.cpp
- src/engine/life_time_system.hpp
- src/engine/physics_system.cpp
- src/game_logic/damage_infliction_system.cpp
- src/game_logic/entity_configuration.ipp
- src/game_logic/entity_factory.cpp
- src/game_logic/interaction/elevator.cpp
- src/ingame_mode.cpp
- test/test_elevator.cpp
- test/test_physics_system.cpp
Introduce a mechanism to activate/deactivate entities according to certain rules. Based on that, implement the following two features:
* Make projectiles disappear when they get off-screen
* Make collectable items only fall down once they come into view
Closes #82
> Introduce an 'active region' for entities

- src/engine/entity_activation_system.cpp
- src/engine/entity_activation_system.hpp
- src/ingame_mode.cpp
Even if the scroll offset doesn't change, entities might change their
positions, which should be reflected in their activation state.
This commit returns the activation system's implementation to its original
design. The 'mPreviousScrollOffset' was an erroneous optimization attempt.
> Fix: Always update entity activation

- src/game_logic/entity_configuration.ipp
- src/ingame_mode.cpp
- src/ingame_mode.hpp
Prevents exiting the level in the wrong spot on e.g. L5.
> Only exit if level exit trigger on screen

- src/game_logic/ai/blue_guard.cpp
- src/game_logic/ai/blue_guard.hpp
When a blue guard stops using a terminal, it won't attack the player
until it has walked at least one step, even if all other conditions
for attack are fulfilled.
closes #161
> Implement subtle blue guard behavior

- src/CMakeLists.txt
- src/data/game_traits.hpp
- src/data/song.hpp
- src/engine/imf_player.cpp
- src/engine/imf_player.hpp
- src/engine/sound_system.cpp
- src/engine/sound_system.hpp
- src/game_main.cpp
- src/game_main.ipp
- src/loader/adlib_emulator.hpp
- src/loader/audio_package.cpp
- src/loader/music_loader.cpp
- src/loader/music_loader.hpp
- src/loader/resource_loader.cpp
- src/loader/resource_loader.hpp
Render music data (AdLib commands from IMF files) on the fly instead of doing an up-front rendering. This reduces loading times and memory usage.
closes #4
> Music playback overhaul

- src/engine/rendering_system.cpp
- src/engine/sprite_tools.hpp
- src/engine/texture.hpp
- src/engine/visual_components.hpp
- src/game_logic/ai/sliding_door.cpp
- src/game_logic/entity_configuration.ipp
- src/game_logic/entity_factory.cpp
- src/game_logic/entity_factory.hpp
- src/game_logic/player/animation_system.cpp
Performance and memory usage optimization. Data structures for sprites are reorganized to only include a single pointer to the required data (`SpriteDrawData`), instead of a `vector` of `SpriteFrame` objects which have pointers to the textures. The list of `SpriteFrames` is the same for all sprites based on the same actor ID, but previously, each instance of a sprite would contain its own copy of that information. By getting rid of this redundant information, `sizeof(Sprite)` goes down from `72` to `48`, plus all the memory required for the `SpriteFrame` lists isn't needed anymore. 
More importantly, this reorganization allows caching the data on a coarser granularity, by mapping from actor ID to `SpriteDrawData*`, therefore reducing the amount of work required to create a sprite in the …
> Sprite data reorg

- src/engine/rendering_system.cpp
- src/engine/sprite_tools.hpp
- src/game_logic/entity_configuration.ipp
- src/game_logic/entity_factory.cpp
- src/ingame_mode.cpp
- src/ingame_mode.hpp
The time required to show the loading screen with fade-in and fade-out is now longer than the time required to actually load the level.
> Remove loading screen

- src/engine/sprite_tools.hpp
This was accidentally broken in #184 - instead of using the sprite's currently showing frame,
the first frame was always used, thus breaking the syncrhonization of bounding box to animation.
> Fix bounding box <-> sprite animation synchronization

- src/main.cpp
We don't need any features from 3.2, so we can just ask for version 3.0 instead. This makes the game work on Intel integrated chipsets.
closes #172 
closes #171
> Lower down the minimum required OpenGL version

- src/base/spatial_types.hpp
- src/data/tile_attributes.cpp
- src/data/tile_attributes.hpp
- src/engine/collision_checker.cpp
- src/engine/collision_checker.hpp
- src/engine/debugging_system.cpp
- src/engine/physics_system.cpp
- src/engine/physics_system.hpp
- src/game_logic/ai/sliding_door.cpp
- src/game_logic/ai/sliding_door.hpp
- src/ingame_mode.cpp
- test/test_elevator.cpp
- test/test_physics_system.cpp
Previously, there was a lot of duplication between `CollisionChecker` and `PhysicsSystem`, with each of them having different capabilities - most notably, the `CollisionChecker` was lacking collisions against solid bodies and behaving incorrectly with tiles that aren't completely solid. This branch moves all collision checking logic into `CollisionChecker`, giving it all of the capabilities the `PhysicsSystem` has, and implements the latter in terms of the former.
This greatly improves code quality, and also fixes a bunch of issues:
Fixes #174 
Fixes #112 
Closes #169 
Closes #168
> Cleanup, refactor and fix collision detection

- src/CMakeLists.txt
- src/engine/rendering_system.cpp
- src/engine/timing.cpp
- src/engine/timing.hpp
- src/engine/visual_components.hpp
- src/game_main.cpp
- src/game_runner.cpp
- src/game_runner.hpp
- test/CMakeLists.txt
- test/test_timing.cpp
Make the game run roughly as fast as if playing the original on a 486 PC: At 15 FPS. Before, it was running at 17.5, which is the theoretical maximum speed the original game could run at when set to the default game speed, and updating/rendering would take 0 time. That's not the case on a period-appropriate system, and measurements have shown that the game runs at roughly 14 to 15.5 FPS on 486-class machines.
While 15 FPS doesn't exactly match the speed on real hardware, it's much closer than before, and also has the added benefit of nicely fitting into the rendering frame rate of 60 FPS RigelEngine usually runs at.
> More accurate game speed

- src/game_logic/player.cpp
- src/game_logic/player.hpp
- test/test_player.cpp
Sometimes, jump button presses would be ignored, especially noticeable when walking down downward slopes. This fixes it.
> Prevent jump button presses getting lost

- src/game_logic/player.cpp
- src/game_logic/player.hpp
- test/test_player.cpp
In the original, movement is possible immediately after the interaction animation has ended. RigelEngine had one additional frame where the player couldn't move. This fixes it.
> Fix interaction anim

- README.md
The built-in macOS unarchiver seems to have a hard time unarchiving the shareware `4duke.zip` file download. I used the terminal utility `unzip`, which unarchived it fine. It can be used for the `.SHR` file as well.
> Add a note re macOS unable to unarchive the zip

- CMakeLists.txt
This fixes errors/warnings when compiling under Visual Studio 19 version 16.1.1.
> Specify exception handling mode for Visual Studio

- src/base/warnings.hpp
- src/data/movie.hpp
- src/game_logic/player.cpp
Clang 8 introduces a few new warnings which we need to ignore/fix.
Fixes #360
> Fix building on newer versions of Clang

- CMakeLists.txt
- README.md
Based on the discussion in https://github.com/lethal-guitar/RigelEngine/issues/360, make it possible to build RigelEngine without treating warnigns as errors. This is to make life easier for those who would like to use RigelEngine, but have no pre-built binaries available for their platform, and who aren't interested in developing.
> Make it possible to disable treating warnings as errors

- README.md
Building on windows with vcpkg requires one to specify the platform type both in vcpkg as well as cmake, otherwise it creates x86 project of Visual Studio. This can alternatively be set in environmental variables. But it is less error-prone this way. Using these commands also automatically finds and uses SDL and Boost libraries.
> Updated README with correct instructions to build on Windows

- src/game_runner.cpp
- src/game_session_mode.cpp
- src/ui/duke_script_runner.cpp
Currently one cannot navigate using num pad Enter on menus and in-game. This pull request adds that support.  
(I don't know why whitespaces are being shown up in PR and git doesn't allow to re-edit. I use spaces for indentation)
> Numpad Enter support within the game menus

- src/renderer/renderer.hpp
Without this, functions constructing a StateSaver and returning it have to rely on copy elision in order to work properly, but that's not guaranteed to happen on all compilers in all situations.
Most likely, this is responsible for the up-scaling not working for you @pratikone  Let me know if this fixes it! And sorry about the trouble, not sure why I didn't run into this, but it's clearly an oversight on my part.
> Implement correct move-semantics for Renderer::StateSaver

- src/renderer/upscaling_utils.cpp
Doing some more testing, I noticed that the viewport calculation for widescreen mode didn't use the full available width of the screen on my laptop, which has a 1280x800 screen (16:10 aspect ratio). With that resolution, the horizontal scale factor works out to 3.33333..., which means we can fit 48 tiles into 1280 pixels (1 tile = 8 px, thus 8*3.333... -> 26.6666. 1280/26.6666 -> 48). But due to rounding too early, the calculation would work out to 47 tiles instead, leaving a gap of 13 pixels on each side of the screen.
> Fix widescreen mode for low resolution 16:10 screen.

- src/game_logic/player/projectile_system.cpp
At first, I incorrectly implemented the ship laser to stop when hitting
an enemy.
This commit also fixes an issue with the reactor debris impact effect,
which would occur every frame after the projectile hit an enemy, instead
of only when it actually hits one.
Run `git diff 132729146a36d5ce7dea60d5144822f36862ea0f~1 -- src/game_logic/player/projectile_system.cpp` to see how the diff should actually have looked like in #461 to be correct from the start:
```
diff --git a/src/game_logic/player/projectile_system.cpp b/src/game_logic/player/projectile_system.cpp
index f78f940..449cec6 100644
--- a/src/game_logic/player/projectile_system.cpp
+++ b/src/game_logic/player/projectile_system.cpp
@@ -108,7 +108,7 @@ void spawnRocketWallImpactEffect(
}
-void spawnRocketEnemyImpactEffect(
+void …
```
> Fix: Ship laser passes through enemies

- CMakeLists.txt
- modding_tools/CMakeLists.txt
- modding_tools/user_profile_tool.cpp
- src/common/user_profile.cpp
- src/common/user_profile.hpp
- src/loader/file_utils.cpp
- src/loader/file_utils.hpp
Adds a new standalone executable called `UserProfileTool`, which can convert between binary and JSON encoding. This makes it easier to inspect and modify the user profile with a text editor, without changing the way the game itself stores the profile.
@pratikone what do you think?
Closes #460
> Add User Profile conversion tool

- src/anti_piracy_screen_mode.cpp
- src/game_main.cpp
- src/game_main.ipp
- src/game_runner.cpp
- src/game_runner.hpp
- src/intro_demo_loop_mode.cpp
- src/menu_mode.cpp
- src/sdl_utils/ptr.hpp
- src/ui/duke_script_runner.cpp
- src/ui/duke_script_runner.hpp
- src/ui/episode_end_sequence.cpp
This PR adds game controller functionality to the engine. It also adds game controller support for most of the menus (not all especially those related to typing).
The sticks and dpad are used for movement (only dpad during the menus). B and A for jump, X and Right shoulder for fire.
For the menus, dpad for the movement, A to select and B for exit.
It has been tested with xbox one controller on Windows. Needs testing on other OSes and other controllers like PS 4 controller and Nintendo Switch one.
> GameController functionality for playing Duke and menus

- .travis.yml
- src/CMakeLists.txt
- src/common/command_line_options.hpp
- src/common/game_service_provider.hpp
- src/engine/movement.cpp
- src/game_logic/game_world.cpp
- src/game_logic/game_world.hpp
- src/game_logic/ingame_systems.cpp
- src/game_logic/player.cpp
- src/game_logic/player.hpp
- src/game_logic/player/damage_system.cpp
- src/game_logic/player/damage_system.hpp
- src/game_main.cpp
- src/game_main.hpp
- src/game_main.ipp
- src/game_runner.cpp
- src/game_runner.hpp
- src/main.cpp
- test/utils.hpp
Implements a god mode as requested by #505. I chose to implement the god mode as a "debug" feature, which means the game has to be started with a command line argument `-d` to enable debug tools. Then, pressing `F10` toggles god mode on and off. I've chosen `F10` instead of `F12`, since `F12` might be used for taking screenshots in the future (see #412).
When god mode is on, the player takes no damage, not even from force fields/reactors. However, the player still dies when falling into a bottomless pit.
Also, fixes the conveyor belt issue found in N7, and puts debugging tools behind a command line switch, to avoid accidentally triggering debugging features during regular gameplay.
Closes #505 
Fixes #506
> Godmode and fixes

- src/common/command_line_options.hpp
- src/game_main.cpp
- src/main.cpp
When specifying a level to jump to on the command line, it's now possible to also specify the difficulty.
Pass `--difficulty <DIFF>`, with `<DIFF>` being one of `easy`, `medium` or `hard`.
When no difficulty is specified, medium is chosen.
Closes #544
> Add option to specify difficulty when jumping to level via command line

- src/game_main.cpp
- src/renderer/opengl.cpp
- src/renderer/renderer.cpp
A couple of changes to make OpenGL usage more robust:
* Use GLSL 130 instead of 150 on non-Apple platforms. Some graphics cards support OpenGL 3.0, But don't support GLSL 150. See #374 for an example.
* Check for errors when loading GL function pointers. This should prevent segfaults due to uninitialized function pointers as seen in #539, and turn them into an error message instead.
> OpenGl robustness

- src/CMakeLists.txt
- src/game_logic/entity_configuration.ipp
- src/game_logic/entity_factory.cpp
- src/game_logic/entity_factory.hpp
- src/game_logic/game_world.cpp
- src/game_logic/game_world.hpp
- src/game_logic/ingame_systems.cpp
- src/game_logic/ingame_systems.hpp
- src/game_logic/player.cpp
- src/game_logic/player.hpp
- src/game_runner.cpp
- src/game_runner.hpp
- src/ui/duke_script_runner.cpp
- src/ui/duke_script_runner.hpp
- src/ui/ingame_menu.cpp
- src/ui/ingame_menu.hpp
- src/ui/menu_navigation_helper.cpp
- src/ui/menu_navigation_helper.hpp
- src/ui/utils.cpp
- src/ui/utils.hpp
Closes #477 
Closes #487
Also fixes music not resetting when dying in a boss level.
Also includes a whole bunch of refactoring, needs thorough testing.
Todo:
> Introduce top-level ingame menu for using ingame menus with gamepad

- src/intro_demo_loop_mode.cpp
- src/menu_mode.cpp
- src/ui/menu_navigation.cpp
I forgot to force push my branch before merging https://github.com/lethal-guitar/RigelEngine/pull/560, bringing in some regressions that I had already fixed locally:
* Space bar stops high score entry, instead of inputting a space
* Only ESC/Button B skip the intro movie, instead of any button press
🤦‍♂️ 
This PR fixes these regressions.
> Apply changes that were meant to be part of the last PR

- src/game_main.cpp
- src/game_runner.cpp
- src/menu_mode.cpp
- src/ui/imgui_integration.cpp
- src/ui/ingame_menu.cpp
- src/ui/ingame_menu.hpp
- src/ui/options_menu.cpp
- src/ui/options_menu.hpp
* All ImGui-based menus are now usable with gamepad and keyboard: Options menu, game path browser, error message display.
* Limits the minimum UI scale in order to make the UI readable on a small screen, like on the Odroid Go Advance.
* Fixes a regression where the game would show left and right of in-game menus when wide-screen mode is on.
In the menus, use D-Pad or arrow keys to select UI elements, confirm/cancel buttons to interact (spacebar/escape on keyboard, A/B or equivalent buttons on gamepad). The UI isn't optimized for small screen sizes yet and looks a bit wonky, but is already perfectly usable on my Odroid. The options menu will see a big overhaul in the future (#404), which should also make it nicer for gamepad navigation, so it doesn't make so much sense to polish it too …
> Full gamepad & keyboard navigation

- CMakeLists.txt
- README.md
- emscripten/Rigel.html
- src/CMakeLists.txt
- src/emscripten_main.cpp
This PR is a refactored and reduced version of #531 where it enabled Rigel Engine to run on the web using webassembly. It uses emscripten library to cross compile to webassembly. The compilation targets are cleanly separated. webassembly related files are only compiled when running under emscripten. A new entry point is provided in emscripten_main.cpp when running under emscripten. More changes are newer variable WEBASSEMBLY_GAME_PATH for providing path of folder containing Duke Nukem II resources. Currently, an html file Rigel.html is copied to build folder which loads the js and wasm. There are more options in Emscripten which can skip this part by directly creating an html file and using a template using --shell-file. It can be explored in the future
Image of rigel engine running in …
> Webassembly changes for running Rigel Engine in a web browser

- src/ui/ingame_menu.cpp
- src/ui/ingame_menu.hpp
- src/ui/text_entry_widget.cpp
- src/ui/text_entry_widget.hpp
Automatically inserts a name when saving the game using a gamepad. This improves the experience for console-like platforms where a keyboard is not available.
Closes #558
> Saved game auto naming

- README.md
- emscripten/shell.html
- src/CMakeLists.txt
- src/data/game_options.hpp
This changes the default window mode to windowed for Emscripten builds, fixing the problem where the game view was partially cut off in the browser window. Switching to fullscreen mode still does not do the right thing currently, leading to a cut off view and mouse position being offset in the options menu. But windowed mode works quite well.
In addition, we are now using the `--shell-file` option instead of a fully handwritten HTML file.
Fixes #569
> More Wasm improvements

- src/CMakeLists.txt
- src/common/command_line_options.hpp
- src/frontend/game.cpp
- src/frontend/game_runner.cpp
- src/game_logic/demo_player.cpp
- src/game_logic/demo_player.hpp
- src/game_logic/entity_configuration.ipp
- src/game_logic/game_world.hpp
- src/main.cpp
Adds a `DemoPlayer` class, which implements demo playback. Due to a few correctness issues that currently prevent the demo from matching the original game, demo playback is not integrated yet into the intro/demo loop.
A command-line option `--play-demo` is added to allow testing demo playback.
First step towards #45
> Implement demo playback facilities

- src/CMakeLists.txt
- src/base/clock.hpp
- src/frontend/game.cpp
- src/frontend/game.hpp
- src/renderer/fps_limiter.hpp
Noticed on the Odroid Go Advance, were the game would skip ahead a couple of frames occasionally. I couldn't get this to happen when using `steady_clock`.
> Fix clock skipping issue on some platforms

- 3rd_party/imgui/imgui_impl_opengl3.cpp
- BUILDING.md
- README.md
- src/frontend/game.cpp
- src/frontend/game.hpp
- src/game_logic/game_world.cpp
- src/game_logic/game_world.hpp
- src/game_main.cpp
- src/renderer/renderer.cpp
- src/renderer/upscaling_utils.cpp
- src/renderer/upscaling_utils.hpp
- src/ui/utils.cpp
- src/ui/utils.hpp
We can now maintain a stable 60 FPS at 1080p on a Raspberry Pi 3 model B, even when water effects are on screen. 
Also new is a loading screen shown at startup, since the game does take a few seconds to start on less powerful machines.
> More Raspberry Pi improvements

- cmake/Modules/FindFilesystem.cmake
This is needed e.g. with gcc 8.3 which defaults to c++14. Without this fix, FindFilesystem.cmake fails to find any valid configuration.
See https://stackoverflow.com/a/47218035/1076564 .
> FindFilesystem.cmake: Fix passing CMAKE_CXX_STANDARD to try_compile

- src/game_logic/game_world.cpp
Quick loading via gamepad menu would briefly show the previous frames sprites on top of  the map from the loaded state.
> Fix visual glitch when quick loading via gamepad

- src/renderer/renderer.cpp
- src/renderer/texture_atlas.cpp
VS was not compiling because of implicit conversion from int to size_t for these variables. I made them static_cast and the errors went away
> Removing implicit type conversion from int to size_t

- emscripten/shell.html
- src/CMakeLists.txt
- src/emscripten_main.cpp
- src/frontend/game.cpp
- src/ui/options_menu.cpp
Fixes #570 
Closes #647 
Closes #648 
And implements "quitting" the game in the wasm version, and a welcome screen with some information:
> Wasm improvements

- src/ui/ingame_menu.cpp
- src/ui/options_menu.cpp
With this, the sound/music toggles are now visible on the OGA.
> Better options menu scaling

- src/engine/random_number_generator.cpp
- src/engine/random_number_generator.hpp
- test/CMakeLists.txt
- test/test_rng.cpp
Hello,
Your CONTRIBUTING.md states that unsigned overflow is usable when useful.
Looks to me like the RNG is quite alright with a uint8_t since it has exactly 256 values (0-255).
Avoids a branch.
Do tell me if I've missed something and that IF has some other reason for being there.
I've also thought about adding a UT for the RNG (since I haven't found one). Just to make sure I didn't break anything. It would largely be doing a 1-1 check against the array tho..
Also, does it intentionally start at 1? i.e. that ++ before the access is there for a good reason right? It confused me a bit!<
Have a good one!
> Use uint8 wraparound for RNG

- src/engine/random_number_generator.cpp
gcc versions up to 9, and all other compilers we use, provide `size_t`
when including `<array>`. This changed with gcc 10, which needs an
explicit include in order for `size_t` to be defined.
Fixes #669
> Add missing include

- .appveyor.yml
- .github/workflows/ci.yml
- BUILDING.md
- CMakeLists.txt
- benchmark/CMakeLists.txt
- benchmark/bench_string_utils.cpp
- cmake/rigel.cmake
- modding_tools/CMakeLists.txt
- src/CMakeLists.txt
- src/base/string_utils.cpp
- src/base/string_utils.hpp
- src/loader/duke_script_loader.cpp
- src/main.cpp
- src/ui/menu_element_renderer.cpp
- test/CMakeLists.txt
- test/test_string_utils.cpp
Hello,
This one resolves #662, partially.
I've started with string `split` since I knew how to implement that.
Funny bit is that it ended up a bit faster than boost's version..
You should check out the benchmarks. I guess that's understandable since this version I added is much simpler and only uses a simple delimiter (one char).
But hey, I'll take it.
EDIT: add `trim[Right|Left]` and `startsWith`
Cheers!
> Remove boost strings split usage

- src/engine/map_renderer.cpp
- src/loader/level_loader.cpp
- src/loader/resource_loader.cpp
- src/loader/resource_loader.hpp
This makes it possible to override tileset and parallax background graphics with png images, in addition to the already existing support for replacing sprite graphics. For now, the replacements still need to be the same size as the original textures, but can contain arbitrary colors. Making it possible to provide higher resolution replacements is the next step.
> Implement asset overrides for tilesets and backdrops

- src/common/game_mode.hpp
- src/engine/map_renderer.cpp
- src/engine/map_renderer.hpp
- src/engine/sprite_factory.cpp
- src/engine/sprite_factory.hpp
- src/engine/tiled_texture.cpp
- src/engine/tiled_texture.hpp
- src/frontend/game.cpp
- src/frontend/game_runner.cpp
- src/frontend/game_runner.hpp
- src/frontend/game_session_mode.cpp
- src/frontend/game_session_mode.hpp
- src/game_logic/game_world.cpp
- src/game_logic/game_world.hpp
- src/loader/actor_image_package.cpp
- src/loader/actor_image_package.hpp
- src/loader/resource_loader.cpp
- src/renderer/texture_atlas.cpp
- src/renderer/texture_atlas.hpp
This makes it possible for replacement sprites/tilesets/backdrops to be higher resolution than the original art. Replacements should be larger by integer multiples only.
> Finish asset replacement for graphics 

- src/game_logic/world_state.cpp
Many thanks to LGR for the awesome video on RigelEngine, and for spotting this bug 😅
> Fix incorrect backdrop when quickloading after teleport in L1

- AUTHORS.md
- src/main.cpp
Implement setting a game path on the command line even if built without Boost (and thus without command line parsing)
> Gamepath without boost

- 3rd_party/imgui-filebrowser/imfilebrowser.cpp
- src/game_main.cpp
- src/main.cpp
MinGW-w64 ships all Windows SDK headers as lowercase, which prevents
cross-compiling this code from Linux.
Windows filesystems are case insensitive so it should work fine with
lowercase includes.
> Make Windows includes lowercase for MinGW

- cmake/Modules/FindSDL2.cmake
According to the [CMake docs](https://cmake.org/cmake/help/latest/module/FindThreads.html), `CMAKE_THREAD_LIBS_INIT` may be empty
even if threads are available. Therefore, we should use `Threads_FOUND`
instead. This fixes the build on openSUSE Tumbleweed.
> Fix openSUSE Tumbleweed build

- .appveyor.yml
- .github/workflows/ci.yml
- CMakeLists.txt
Introduce cmake build options
* BUILD_BENCHMARKS - build benchmarks (OFF by default)
* BUILD_MODDING_TOOLS - Build modding tools (OFF by default)
> cmake: Add BUILD_MODDING_TOOLS and BUILD_TESTS

- src/engine/map_renderer.cpp
- src/engine/map_renderer.hpp
- src/frontend/game_runner.cpp
- src/frontend/game_runner.hpp
- src/game_logic/debugging_system.cpp
- src/game_logic/dynamic_geometry_components.hpp
- src/game_logic/dynamic_geometry_system.cpp
- src/game_logic/dynamic_geometry_system.hpp
- src/game_logic/entity_factory.cpp
- src/game_logic/game_world.cpp
- src/game_logic/world_state.cpp
- src/game_logic/world_state.hpp
> Smooth dynamic geometry

- BUILDING.md
- CMakeLists.txt
- cmake/rigel_sanitizers.cmake
* cmake build type == Asan will add the required flags (fsanitizer and
-fno-omit-frame-pointer alongside the debug flags
* helpful messages are printed to see the build type
* usage with ctest is described in the BUILDING.md file
> Add option to run tests with ASan #244

- src/CMakeLists.txt
- src/assets/resource_loader.cpp
- src/assets/resource_loader.hpp
- src/assets/voc_decoder.cpp
- src/assets/voc_decoder.hpp
- src/audio/sound_system.cpp
- src/audio/sound_system.hpp
- src/base/audio_buffer.hpp
Hello, @lethal-guitar check this out!
close #816
- Move `src/data/audio_buffer.hpp` to `src/base`
- Adapt all `#include` preprocessors in client code
- Adapt header file code form `namespace data` to `namespace base`
- Adapt client code from  namespace`data::` to `base::`
> Move `src/data/audio_buffer.hpp` to `src/base`

- src/data/bonus.hpp
- src/data/player_model.cpp
- src/data/player_model.hpp
- src/frontend/demo_player.cpp
- src/frontend/demo_player.hpp
- src/frontend/game_runner.cpp
- src/frontend/game_runner.hpp
- src/frontend/game_session_mode.cpp
- src/frontend/game_session_mode.hpp
- src/game_logic/damage_infliction_system.cpp
- src/game_logic/damage_infliction_system.hpp
- src/game_logic/game_world.cpp
- src/game_logic/game_world.hpp
- src/game_logic/player.cpp
- src/game_logic/player.hpp
- src/game_logic/player/interaction_system.cpp
- src/game_logic/player/interaction_system.hpp
- src/game_logic/world_state.cpp
- src/game_logic/world_state.hpp
- src/game_logic_classic/game_world_classic.cpp
- src/game_logic_classic/game_world_classic.hpp
- src/ui/hud_renderer.cpp
- src/ui/hud_renderer.hpp
- src/ui/ingame_menu.cpp
- src/ui/ingame_menu.hpp
- test/test_elevator.cpp
- test/test_letter_collection.cpp
- test/test_player.cpp
- test/test_spike_ball.cpp
Hey @lethal-guitar 
This PR:
1. Addresses and closes #878 
2. Renames `PlayerModel` class and types of `PlayerModel*` to `PersistentPlayerState`
3. `RenamempPlayerModel -> mpPersistentPlayerState`, `pPlayerModel -> pPersistentPlayerState`
Edit: `clang-format` CI task fails, it seems it totally slipped my mind.
> Rename `PlayerModel` class to `PersistentPlayerState`

- src/frontend/user_profile.cpp
> Store gamepath in `Options.json`
